name: PR Title Checker
on:
  pull_request_target:
    branches:
      - develop
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  pull_request:
    name: PR Title Checker
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.3.4
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: '.github/pr-title-checker-config.json'
