name: "CI | Cognigy-CLI Sonar"

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  sonarqube:
    name: "Cognigy-CLI - SonarQube Analysis"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarqube-scan-action@v7
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        env:
          SONAR_TOKEN: ${{ secrets.NICE_SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.NICE_SONAR_HOST_URL }}
